### ISSUE TITLE
3D printing files

### ISSUE THREAD

**Issue by martinberlin** [Xinyuan-LilyGO/LilyGo-EPD47#10] opened 2021-01-10 16:44 UTC
Comes from #2 :
Thanks @markbirss the intention  of converting the file to 0-sjk_asm(2).zip was great but it really does not help like this. When importing it to blender or even the Slicer software this comes as a single block piece that looks like a solid mobile device and it's really useless for 3D printing. 
Preview:
![Screenshot from 2021-01-10 17-38-35](https://user-images.githubusercontent.com/2692928/104129047-273f5480-536b-11eb-9815-e009b585bfe8.png)

**Comment by kd8bxp** [comment] 2021-01-10 16:53
[T5_EDP47_Case.zip](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/files/5792949/T5_EDP47_Case.zip)
This is mine, as I said in the previous topic, I'm no expert at what I've done. I used FreeCAD and pulled everything apart.
The top seems to be a problem, and maybe I did something wrong.
When you use FreeCAD you can see if  you remove the top, there is a rendering of the T5 display already in the case, there also appears to be a battery (or maybe 2 batteries for the two different models)
The buttons look to me like they will print very small as well, and I'm probably not going to even try to print them.
I am printing the main case now, and can post pictures if it would help.

**Comment by kd8bxp** [comment] 2021-01-10 18:33
Here are pictures from FreeCAD, and I tried again to get the top cover converted to a stl file with no luck.
![Screenshot at 2021-01-10 13-27-22](https://user-images.githubusercontent.com/7252172/104131981-555f6d00-5348-11eb-82b4-0b215fa3e7c5.png)
![Screenshot at 2021-01-10 13-27-49](https://user-images.githubusercontent.com/7252172/104131982-55f80380-5348-11eb-94b5-09a078bc1f14.png)
![Screenshot at 2021-01-10 13-28-12](https://user-images.githubusercontent.com/7252172/104131983-56909a00-5348-11eb-98da-8f619d64ec4a.png)
![Screenshot at 2021-01-10 13-28-21](https://user-images.githubusercontent.com/7252172/104131984-56909a00-5348-11eb-9637-4f9ab973df02.png)
![Screenshot at 2021-01-10 13-28-30](https://user-images.githubusercontent.com/7252172/104131985-57293080-5348-11eb-960c-160166cafc71.png)
![Screenshot at 2021-01-10 13-28-35](https://user-images.githubusercontent.com/7252172/104131986-57293080-5348-11eb-9909-e7dda978bf28.png)
![Screenshot at 2021-01-10 13-28-45](https://user-images.githubusercontent.com/7252172/104131987-57c1c700-5348-11eb-9e15-89331fad1508.png)
![Screenshot at 2021-01-10 13-29-16](https://user-images.githubusercontent.com/7252172/104131988-57c1c700-5348-11eb-96e9-d39aaf82576d.png)
![Screenshot at 2021-01-10 13-29-29](https://user-images.githubusercontent.com/7252172/104131989-57c1c700-5348-11eb-9f05-b48beff34a3b.png)
![Screenshot at 2021-01-10 13-30-06](https://user-images.githubusercontent.com/7252172/104131992-5e503e80-5348-11eb-9351-311d75267c94.png)

**Comment by kd8bxp** [comment] 2021-01-10 18:53
here are a few more pictures from FreeCAD
![Screenshot at 2021-01-10 13-47-32](https://user-images.githubusercontent.com/7252172/104132435-3d3d1d00-534b-11eb-98b7-9c8e1f074806.png)
![Screenshot at 2021-01-10 13-49-10](https://user-images.githubusercontent.com/7252172/104132436-3dd5b380-534b-11eb-9ca1-be8f481de07d.png)
![Screenshot at 2021-01-10 13-49-22](https://user-images.githubusercontent.com/7252172/104132437-3e6e4a00-534b-11eb-8ac4-57b5b1fbb4e1.png)
![Screenshot at 2021-01-10 13-49-39](https://user-images.githubusercontent.com/7252172/104132439-3e6e4a00-534b-11eb-8b02-5de2c97af77e.png)
![Screenshot at 2021-01-10 13-50-39](https://user-images.githubusercontent.com/7252172/104132441-3f06e080-534b-11eb-96c7-5a2816f52dcd.png)
![Screenshot at 2021-01-10 13-50-47](https://user-images.githubusercontent.com/7252172/104132442-3f06e080-534b-11eb-9287-4c87ed1697e7.png)
![Screenshot at 2021-01-10 13-51-01](https://user-images.githubusercontent.com/7252172/104132443-3f06e080-534b-11eb-88f9-b8ab035e3c35.png)
![Screenshot at 2021-01-10 13-51-10](https://user-images.githubusercontent.com/7252172/104132444-3f9f7700-534b-11eb-89df-b512e770a53b.png)
![Screenshot at 2021-01-10 13-51-21](https://user-images.githubusercontent.com/7252172/104132445-3f9f7700-534b-11eb-9549-40e3b0d4d83f.png)

**Comment by kd8bxp** [comment] 2021-01-10 20:38
Print finished, overall, it turned out good - my printer is a little out of level, so some issues with the bottom (but that is me).
I will try to print the buttons, they will be needed.  It will need a top to hold the board in place, but the biggest problem I see with it right now. The USB-C cable will not fully insert into the provided hole, so, no power from USB-C. Here are the pictures of my print, took almost 3 hours, using a Wanhao Duplicator i3 plus, 5% infill, .15mm - no rafts or supports. 
It does kind of look like a phone case, maybe that is what inspired this design (?)
![IMG_20210110_152545774](https://user-images.githubusercontent.com/7252172/104134735-94e28500-5359-11eb-9fd2-b929dd722f7c.jpg)
![IMG_20210110_152554037](https://user-images.githubusercontent.com/7252172/104134743-99a73900-5359-11eb-8d35-167d91edaf20.jpg)
![IMG_20210110_152601123](https://user-images.githubusercontent.com/7252172/104134755-a035b080-5359-11eb-8ca6-b19e028fc3b9.jpg)
![IMG_20210110_152717203](https://user-images.githubusercontent.com/7252172/104134761-a9268200-5359-11eb-854c-53d488ac5185.jpg)
![IMG_20210110_152721062](https://user-images.githubusercontent.com/7252172/104134767-adeb3600-5359-11eb-8a8a-3defe79162c4.jpg)
![IMG_20210110_152728979](https://user-images.githubusercontent.com/7252172/104134773-b2175380-5359-11eb-9cab-5cdaebd2d456.jpg)
![IMG_20210110_152739247](https://user-images.githubusercontent.com/7252172/104134777-b93e6180-5359-11eb-9e16-e05311120dcd.jpg)
![IMG_20210110_153004003](https://user-images.githubusercontent.com/7252172/104134781-bfccd900-5359-11eb-8800-1681daccd94c.jpg)

**Comment by kd8bxp** [comment] 2021-01-10 21:22
Sorry to keep posting like this, but really hoping it helps out in getting a nice case designed for this board. 
I think the buttons need a little work, the holes just seem too small (at least to me) and to me the buttons seem too short. They printed just fine, in about 2 mins time. They were kind of hard to get in place, but I think it is because the holes were just a little small. 
Also I needed to rotate them to be flat on the build plate, I think this could be fixed if I really knew what I was doing when I took apart the larger file. 
![IMG_20210110_161135169](https://user-images.githubusercontent.com/7252172/104135677-a4fd6300-535f-11eb-83c0-4ceb45d7f604.jpg)
![IMG_20210110_161625176](https://user-images.githubusercontent.com/7252172/104135679-a7f85380-535f-11eb-8e5e-7654315a0d2f.jpg)
![Screenshot at 2021-01-10 15-56-39](https://user-images.githubusercontent.com/7252172/104135683-aa5aad80-535f-11eb-9f73-ff3331aa25c4.png)

**Comment by lewisxhe** [comment] 2021-01-11 01:58
The new 3D files will be available on the 13th, and the ones on github need to be converted to STL before they can be used.

![U`KW5G}9W(XUEDSICV2TS0E](https://user-images.githubusercontent.com/22990954/104141802-7f219e00-53f3-11eb-937f-bd49b07ee607.jpg)

**Comment by kd8bxp** [comment] 2021-01-11 05:58
@lewisxhe Looking forward to the new case, image looks good.
It looks like you did some work on the USB-C connector.  What about the buttons, are they a little bigger?

**Comment by martinberlin** [comment] 2021-01-11 14:58
Nice, so I have to use Cura then? 
Can it import this **stp** files directly?
I've a Prusa printer and mostly use Slic3r that is a different software to slice 3D Models.

**Comment by kd8bxp** [comment] 2021-01-11 16:57
@martinberlin  no cura uses stl files, I used FreeCAD to convert the STP pull apart the STP file, and convert it the pieces to STL
Cura is just the slicer I use, mainly because it was free and worked with my printer. 
https://www.freecadweb.org/ it's a large download, but it is in the Ubuntu repository if you are using linux, you can get it for Windows and Mac as well.

**Comment by martinberlin** [comment] 2021-01-11 18:24
Can you please upload the STL files here or in Thingiverse so I don't have to install Freecad?
Thanks a lot in advance (Github let's you just drag & drop zip files in Issues)

**Comment by kd8bxp** [comment] 2021-01-11 19:59
already did see above (https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/issues/10#issuecomment-757507333)
it has a problem with the top, and I think the buttons are too small.
Also @lewisxhe said a new 3d file is going to be published on the 13th in a couple of days.

**Comment by lewisxhe** [comment] 2021-01-14 03:07
@martinberlin  @kd8bxp STL file has been uploaded

**Comment by kd8bxp** [comment] 2021-01-14 05:54
@martinberlin  Pulled apart the stp file again, here is what I came up with. hopefully it will help, still looking to get a nice case for this display. 

This is the bottom, and the frame in two separated stl files.
[alternativestls.zip](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/files/5812524/alternativestls.zip)

This is the bottom and the frame as one print 
[caseT5-2.zip](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/files/5812526/caseT5-2.zip)

This is the buttons - they will need to be rotated to fit correctly on the build plate of your printer, there is also a file called "needed?.stl" when I pulled apart the stp file, it looks like some extras maybe to make the buttons longer and fit better - I'm not sure about them. 
[buttons.zip](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/files/5812527/buttons.zip)

It looks like someone will need to design a top, when I pulled apart the stp the top just came out as a whole piece again, without a hole for the display.

Hope this helps, I'm going to print mine in the morning, and can post some photos of it when it is finished.

**Comment by kd8bxp** [comment] 2021-01-14 05:58
Here are some pictures from freeCAD
![Screenshot at 2021-01-14 00-01-30](https://user-images.githubusercontent.com/7252172/104550643-4821d700-5603-11eb-8aab-1f95049c3788.png)
![Screenshot at 2021-01-14 00-02-57](https://user-images.githubusercontent.com/7252172/104550647-48ba6d80-5603-11eb-8147-d55c103cfdb0.png)
![Screenshot at 2021-01-14 00-12-48](https://user-images.githubusercontent.com/7252172/104550649-49530400-5603-11eb-86dc-668a793ae55a.png)
![Screenshot at 2021-01-14 00-12-59](https://user-images.githubusercontent.com/7252172/104550651-49530400-5603-11eb-8f9c-437f6047f6c0.png)
![Screenshot at 2021-01-14 00-14-01](https://user-images.githubusercontent.com/7252172/104550652-49eb9a80-5603-11eb-9051-39ef2c121da8.png)

Below is the extra pieces for the button, which I'm not sure if they are needed or not, see the above comment -I suspect they will be needed, but until I get the case printed, it is hard to say.
![Screenshot at 2021-01-14 00-02-11](https://user-images.githubusercontent.com/7252172/104550768-8b7c4580-5603-11eb-8253-350dbdda3d0a.png)

**Comment by martinberlin** [comment] 2021-01-14 09:51
Good work, looks much better. Do not forget to activate supports when printing this model!

**Comment by kd8bxp** [comment] 2021-01-15 21:07
Here are my thoughts on the 2nd version of the case.
1) USB-C still not useable
2) Buttons need to be longer (taller), the radius of them appears to be correct. The holes in the frame are too small, the buttons are very very tight and hard to push into the case itself. The hole needs to be slightly larger radius.
3) Still needs a top, After talking a bit to @martinberlin on twitter, we decided the case was designed with the touch screen being used. Need a top for those of us who don't have the touch screen.
4) need a bottom for the case that doesn't have the hole for the 18650 battery (for those of us that are using a lipo) 

I know it's hard to see in these pictures, but I try to show the USB-C cable is still too short to fit, the easy fix for this is to make the hole for the USB-C larger, so that the plastic around the connector can also fit into the case (I took a rotatary tool and made the hole larger, this worked, so probably needs to be in the design).

![IMG_20210114_145342093](https://user-images.githubusercontent.com/7252172/104778116-d8b6ff00-574a-11eb-9c77-c05e21388f97.jpg)
![IMG_20210114_145350887](https://user-images.githubusercontent.com/7252172/104778125-de144980-574a-11eb-9308-2b50fd2d75c9.jpg)

Over all the case printed nicely:
![IMG_20210114_145401768_HDR](https://user-images.githubusercontent.com/7252172/104778168-eff5ec80-574a-11eb-9666-8d86cc93787f.jpg)
![IMG_20210114_145409269_HDR](https://user-images.githubusercontent.com/7252172/104778188-f71cfa80-574a-11eb-84ae-4dd820200fc2.jpg)

Here is the 1st version compared to the 2nd version:
![IMG_20210114_145424079_HDR](https://user-images.githubusercontent.com/7252172/104778243-0ef47e80-574b-11eb-880f-b325b6422201.jpg)

2nd version with the T5 in place:
![IMG_20210114_145548868_HDR](https://user-images.githubusercontent.com/7252172/104778292-203d8b00-574b-11eb-8dc1-227714d332cd.jpg)
![IMG_20210114_145553520_HDR](https://user-images.githubusercontent.com/7252172/104778299-229fe500-574b-11eb-88b1-49909bc705e5.jpg)
![IMG_20210114_145558887_HDR](https://user-images.githubusercontent.com/7252172/104778319-2895c600-574b-11eb-93a1-1fc4deaa48c5.jpg)

very hard to see the button problem - (I think probably just making the holes slightly larger will fix at least one issue) The buttons are flush with the case, and nearly impossible to push (have to really force them to get them into the hole, even after cleaning the hole with a drill bit) it's an very tight fit.
![IMG_20210114_150645022_HDR](https://user-images.githubusercontent.com/7252172/104778437-54b14700-574b-11eb-9004-91c93fefd278.jpg)

This is the USB-C cable after I cut the hole bigger:
![IMG_20210115_154612879](https://user-images.githubusercontent.com/7252172/104778596-a0fc8700-574b-11eb-8d6e-8d79419cbab1.jpg)
![IMG_20210115_154619727](https://user-images.githubusercontent.com/7252172/104778610-a5c13b00-574b-11eb-859c-59f85958c026.jpg)
![IMG_20210115_154628336](https://user-images.githubusercontent.com/7252172/104778631-ac4fb280-574b-11eb-9bae-e048ec99cd79.jpg)
![IMG_20210115_154703785](https://user-images.githubusercontent.com/7252172/104778644-b40f5700-574b-11eb-9280-b4403e2451c7.jpg)

**Comment by kd8bxp** [comment] 2021-01-15 21:48
Forgot to put the size of the USB-C hole after I cut it out a bit:

TOP to BOTTOM 7.0mm to 7.5mm (I used a rotary cutting tool, so it's not percsie at all)
SIDE TO SIDE: 12.4mm to 12.6mm
These are all approximate - I would probably error on making the hole bigger then smaller. So 12.6 and 7.5mm 

My USB-C cables is 6.0mm and 10.5mm approximate.  so the above numbers seem to good size for the hole. 
![IMG_20210115_164511443](https://user-images.githubusercontent.com/7252172/104781915-5aaa2680-5751-11eb-9c85-cca55f032ca9.jpg)
![IMG_20210115_164552250](https://user-images.githubusercontent.com/7252172/104781929-63026180-5751-11eb-8bd3-07df0f80f541.jpg)

**Comment by martinberlin** [comment] 2021-03-01 18:06
Totally agree with the USB-C size. It should fit most common connectors out of the printer, I also had to enlarge mine with a cutter and looks quite bad ;)

**Comment by martinberlin** [comment] 2021-03-02 10:17
**Warning:** If you assemble the touch overlay take great are when connecting the small flat cable. The connector in the Lilygo PCB is not meant to open and close many times. I got one broken just by trying to get it inside the 3D printed housing.

The touch connector needs a small 3D printed part so the cable is not doing an inverted U form to the top. Otherwise is very dangerous to put it in such a small housing because you risk breaking it (Like I did)
Either it needs to be more flat to the PCB (is too large for this)
or this side of the 3D model should give a bit more space to avoid making pressure on the small FPC cable when mounting it inside the housing.

**Comment by kd8bxp** [comment] 2021-03-07 22:35
@martinberlin Nice again, I am printing it now using PLA (only material I have at the moment), thanks for the update

**Comment by guyou** [comment] 2021-03-11 12:25
Please, note that we can find more models on platforms like tingiverse. Examples:
- https://www.thingiverse.com/thing:4782302
- https://www.thingiverse.com/thing:4749075

**Comment by martinberlin** [comment] 2021-03-11 13:23
Second one looks nice. But attention that the buttons seem all in one piece, I guess that is supposed to break and move, but I'm not sure if it will work like expected with all printers. I've printed mine with the original in 2 pieces, the down part closed in PLA, the sides in FLEX. Looks nice, waiting for the new epaper since I give mine to a friend!

**Comment by kd8bxp** [comment] 2021-03-11 17:27
@guyou Thank you for sharing, I think I like the 1st one a bit more - And they look like they solve at least some of the problems with having a bezel for the model without the touch screen.
Again thanks for sharing.

**Comment by kd8bxp** [comment] 2021-03-12 07:53
@martinberlin @guyou  I printed both cases from above, over all I like both, but the 2nd one does seem to work better. (It really depends on what you want to do with your display thou.) 

I am still having some issues with the buttons (on both cases, but over all these are good.)

So This is my print of https://www.thingiverse.com/thing:4782302
![IMG_20210311_195511164_HDR](https://user-images.githubusercontent.com/7252172/110908515-eb7a2a00-82dc-11eb-811e-5b61256f9c62.jpg)
With the buttons in place, the display is held in place - without the buttons, the display will fall. The USB-C connector is on the bottom, there is no room for a 90 degree adapter - the author of the case said they are running on battery. So this is great for that.  
I want to try to make a base that will raise it up so that either a USB-C or a 90 degree adapter will fit under it.

The 2nd case: https://www.thingiverse.com/thing:4749075

![IMG_20210312_022549157](https://user-images.githubusercontent.com/7252172/110908856-66dbdb80-82dd-11eb-89c2-573be4658a52.jpg)
The buttons are better on this one - but very hard to break loose, with the thumb screw in place it works good. And the USB-C connector is easy enough to use. 
The original STL file has the screw holder next to the case, which for me just pushed the print outside of my printer.
I did a small remix where I moved the holder to the inside of the case while it's printing, this saved some room, and only increased the print time by about 4 minutes. I think that is a good trade off. 
My "remix" is here: https://www.thingiverse.com/thing:4791483 
But I really don't like calling this a remix - because it's more of a move. nothing else was changed. 

@guyou thanks again for sharing these cases.

**Closed** 2022-09-02 06:56 UTC
